routes/produto_atualizar.py
from flask import Blueprint, render_template, request, redirect, url_for
from routes.models import db, Produto

atualizar_routes = Blueprint('atualizar_routes', __name__)

@atualizar_routes.route("/atualizar/<int:idProduto>", methods=['POST', 'GET'])
def atualizar(idProduto):
    produto = Produto.query.filter_by(idProduto = idProduto).first()

    if request.method == 'POST':
        nome = request.form.get("nome")
        descricao = request.form.get("descricao")
        valor = request.form.get("valor")
    
        if nome and descricao and valor:
            produto.nome = nome
            produto.descricao = descricao
            produto.valor = valor

            db.session.commit()

            return redirect(url_for("listar_routes.lista"))
    
    return render_template("atualizar.html", produto=produto)

routes/produto_cadastro.py
from flask import Blueprint, render_template, request, redirect, url_for
from routes.models import db, Produto

cadastrar_routes = Blueprint('cadastrar_routes', __name__)

@cadastrar_routes.route("/produto/cadastrar")
def cadastrar():
    return render_template("cadastro.html")

@cadastrar_routes.route("/cadastro", methods=['POST', 'GET'])
def cadastro():
    if request.method == 'POST':
        nome = request.form.get("nome")
        descricao = request.form.get("descricao")
        valor = request.form.get("valor")
    
    if nome and descricao and valor:
        p = Produto(nome, descricao, valor)

        db.session.add(p)
        db.session.commit()
    
    return redirect(url_for("index"))

routes/produto_excluir.py
from flask import Blueprint, render_template, redirect, url_for
from routes.models import db, Produto

excluir_routes = Blueprint('excluir_routes', __name__)

@excluir_routes.route("/excluir/<int:idProduto>")
def excluir(idProduto):
    produto = Produto.query.filter_by(idProduto = idProduto).first()

    if produto:
        db.session.delete(produto)
        db.session.commit()

    produtos = Produto.query.all()

    return render_template("lista.html", produtos = produtos)

routes/usuario_cadastro.py
from flask import Blueprint, render_template, request, redirect, url_for
from routes.models import db, Usuario

usuario_cadastro_routes = Blueprint('usuario_cadastro', __name__)

@usuario_cadastro_routes.route("/cadastro-usuario", methods=['GET', 'POST'])
def cadastro_usuario():
    if request.method == 'POST':
        email = request.form.get("email")
        senha = request.form.get("senha")

        if email and senha:
            usuario_existente = Usuario.query.filter_by(email=email).first()

            if usuario_existente:
                flash('Este e-mail já está em uso. Por favor, escolha outro.', 'error')
                return redirect(url_for("pagina_cadastro_login"))

            novo_usuario = Usuario(email, senha)

            db.session.add(novo_usuario)
            db.session.commit()
    
            return redirect(url_for("pagina_cadastro_login"))
    
    return render_template("cadastro_usuario.html")

templates/adicionar_produto.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>S4 SUPRIMENTOS</title>
    <style>
        body {
            background: linear-gradient(to right, #ffffff, #ff6b00);
            margin: 0;
            font-family: Arial, sans-serif;
        }

        .header {
            background-color: #ececec;
            text-align: center;
            padding: 15px 0;
        }

        .header img {
            max-width: 100%;
            height: auto;
        }

        .separator {
            border-bottom: 1px solid rgb(60, 60, 60);
            /* Reduzindo a espessura da linha */
            box-shadow: 0 2px 4px rgb(37, 37, 37);
            /* Ajustando o tamanho da sombra */
        }

        .container {
            font-weight: bold;
            font-size: 20px;
            display: flex;
            justify-content: center;
            align-items: center;
            margin-top: 60px;
            margin-left: auto;
            margin-right: auto;
            padding: 20px;
            width: 415px;
            height: 400px;
            border-radius: 20px;
            background-color: #ffffff;
            flex-direction: column;
            box-shadow: inset 0 0 10px rgb(180, 180, 180);
        }

        .button {
            text-decoration: none;
            display: flex;
            justify-content: center;
            align-items: center;
            width: 150px;
            height: 30px;
            margin-top: 50px;
            padding: 10px 20px;
            border-radius: 30px;
            border: none;
            background-color: #ff6b00;
            color: white;
            font-size: 16px;
            cursor: pointer;
            text-align: center;
        }

        .button-submit {
            cursor: pointer;
            display: flex;
            justify-content: center;
            cursor: pointer;
        }

        input {
            font-size: 16px;
            margin-top: 30px;
            padding: 12px 20px;
            border-radius: 30px;
            border-color: #ff6b00;
        }

        form{
            justify-content: center;
            align-items: center;
        }
    </style>
</head>

<body>
    <div class="header">
        <img
            src="https://static.wixstatic.com/media/b6c7e5_b6d43044bb344d83bb6a97a6875ea924~mv2.png/v1/crop/x_26,y_122,w_400,h_196/fill/w_112,h_55,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Nova%20Logo%20-%20s4.png">
    </div>
    <div class="separator"></div>
    <div class="container">Cadastrar Produto
        <form action="{{ url_for('cadastrar_routes.cadastro_produto')}}" method="POST">
            <div><input type="text" name="nome" autocomplete="off" placeholder="Produto:"></div>
            <div><input type="text" name="descricao" autocomplete="off" placeholder="Descrição do produto:"></div>
            <div><input type="number" name="valor" placeholder="Valor:"></div>
            <div class="button-submit"><input type="submit" value="Adicionar Produto"></div>
        </form>
    </div>
</body>

</html>

templates/atualizar.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>S4 SUPRIMENTOS</title>
    <style>
        body {
            background: linear-gradient(to right, #ffffff, #ff6b00);
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
        }

        .header {
            background-color: #ececec;
            text-align: center;
            padding: 15px 0;
        }

        .header img {
            max-width: 100%;
            height: auto;
        }

        .separator {
            border-bottom: 1px solid rgb(60, 60, 60);
            /* Reduzindo a espessura da linha */
            box-shadow: 0 2px 4px rgb(37, 37, 37);
            /* Ajustando o tamanho da sombra */
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            margin-top: 60px;
            margin-left: auto;
            margin-right: auto;
            padding: 20px;
            width: 415px;
            height: 400px;
            border-radius: 20px;
            border: 1px solid #ff6b00;
            background-color: #ffffff;
            flex-direction: column;
            box-shadow: inset 0 0 10px rgb(180, 180, 180);
        }

        .button {
            text-decoration: none;
            display: flex;
            justify-content: center;
            align-items: center;
            width: 150px;
            height: 30px;
            margin-top: 50px;
            padding: 10px 20px;
            border-radius: 30px;
            border: none;
            background-color: #ff6b00;
            color: white;
            font-size: 16px;
            cursor: pointer;
            text-align: center;
        }

        .button-submit {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .container {
            font-family: madefor-display, 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 22px;
        }

        input {
            font-size: 16px;
            margin-top: 30px;
            padding: 12px 20px;
            border-radius: 30px;
            border-color: #ff6b00;
        }

        form{
            justify-content: center;
            align-items: center;
        }
    </style>
</head>

<body>
    <div class="header">
        <img
            src="https://static.wixstatic.com/media/b6c7e5_b6d43044bb344d83bb6a97a6875ea924~mv2.png/v1/crop/x_26,y_122,w_400,h_196/fill/w_112,h_55,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Nova%20Logo%20-%20s4.png">
    </div>
    <div class="separator"></div>
    <div class="container">Atualizar dados do Produto
        <form action="" method="POST">
            <div><input type="text" name="nome" autocomplete="off" placeholder="Produto:" value="{{ produto.nome }}"></div>
            <div><input type="text" name="descricao" autocomplete="off" placeholder="Descrição do produto:" value="{{ produto.descricao }}"></div>
            <div><input type="number" name="valor" value="{{ produto.valor }}"></div>
            <div class="button-submit"><input type="submit" value="Atualizar Dados"></div>
        </form>
    </div>
</body>

</html>

templates/atualizar_produto.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>S4 SUPRIMENTOS</title>
    <style>
        body {
            background: linear-gradient(to right, #ffffff, #ff6b00);
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
        }

        .header {
            background-color: #ececec;
            text-align: center;
            padding: 15px 0;
        }

        .header img {
            max-width: 100%;
            height: auto;
        }

        .separator {
            border-bottom: 1px solid rgb(60, 60, 60);
            /* Reduzindo a espessura da linha */
            box-shadow: 0 2px 4px rgb(37, 37, 37);
            /* Ajustando o tamanho da sombra */
        }

        .container {
            font-weight: bold;
            font-size: 20px;
            display: flex;
            justify-content: center;
            align-items: center;
            margin-top: 60px;
            margin-left: auto;
            margin-right: auto;
            padding: 20px;
            width: 415px;
            height: 400px;
            border-radius: 20px;
            background-color: #ffffff;
            flex-direction: column;
            box-shadow: inset 0 0 10px rgb(180, 180, 180);
        }

        .button {
            text-decoration: none;
            display: flex;
            justify-content: center;
            align-items: center;
            width: 150px;
            height: 30px;
            margin-top: 50px;
            padding: 10px 20px;
            border-radius: 30px;
            border: none;
            background-color: #ff6b00;
            color: white;
            font-size: 16px;
            cursor: pointer;
            text-align: center;
        }

        .button-submit {
            cursor: pointer;
            display: flex;
            justify-content: center;
            cursor: pointer;
        }

        input {
            font-size: 16px;
            margin-top: 30px;
            padding: 12px 20px;
            border-radius: 30px;
            border-color: #ff6b00;
        }

        form{
            justify-content: center;
            align-items: center;
        }
    </style>
</head>

<body>
    <div class="header">
        <img
            src="https://static.wixstatic.com/media/b6c7e5_b6d43044bb344d83bb6a97a6875ea924~mv2.png/v1/crop/x_26,y_122,w_400,h_196/fill/w_112,h_55,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Nova%20Logo%20-%20s4.png">
    </div>
    <div class="separator"></div>
    <div class="container">Atualizar dados do Produto
        <form action="" method="POST">
            <div><input type="text" name="nome" autocomplete="off" placeholder="Produto:" value="{{ produto.nome }}"></div>
            <div><input type="text" name="descricao" autocomplete="off" placeholder="Descrição do produto:" value="{{ produto.descricao }}"></div>
            <div><input type="number" name="valor" value="{{ produto.valor }}"></div>
            <div class="button-submit"><input type="submit" value="Atualizar Dados"></div>
        </form>
    </div>
</body>

</html>

templates/cadastro.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>S4 SUPRIMENTOS</title>
    <style>
        body {
            background: linear-gradient(to right, #ffffff, #ff6b00);
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
        }

        .header {
            background-color: #ececec;
            text-align: center;
            padding: 15px 0;
        }

        .header img {
            max-width: 100%;
            height: auto;
        }

        .separator {
            border-bottom: 1px solid rgb(60, 60, 60);
            /* Reduzindo a espessura da linha */
            box-shadow: 0 2px 4px rgb(37, 37, 37);
            /* Ajustando o tamanho da sombra */
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            margin-top: 60px;
            margin-left: auto;
            margin-right: auto;
            padding: 20px;
            width: 415px;
            height: 400px;
            border-radius: 20px;
            border: 1px solid #ff6b00;
            background-color: #ffffff;
            flex-direction: column;
            box-shadow: inset 0 0 10px rgb(180, 180, 180);
        }

        .button {
            text-decoration: none;
            display: flex;
            justify-content: center;
            align-items: center;
            width: 150px;
            height: 30px;
            margin-top: 50px;
            padding: 10px 20px;
            border-radius: 30px;
            border: none;
            background-color: #ff6b00;
            color: white;
            font-size: 16px;
            cursor: pointer;
            text-align: center;
        }

        .button-submit {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .container {
            font-family: madefor-display, 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 22px;
        }

        input {
            font-size: 16px;
            margin-top: 30px;
            padding: 12px 20px;
            border-radius: 30px;
            border-color: #ff6b00;
        }

        form{
            justify-content: center;
            align-items: center;
        }
    </style>
</head>

<body>
    <div class="header">
        <img
            src="https://static.wixstatic.com/media/b6c7e5_b6d43044bb344d83bb6a97a6875ea924~mv2.png/v1/crop/x_26,y_122,w_400,h_196/fill/w_112,h_55,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Nova%20Logo%20-%20s4.png">
    </div>
    <div class="separator"></div>
    <div class="container">Cadastrar Produto
        <form action="{{ url_for('cadastrar_routes.cadastro')}}" method="POST">
            <div><input type="text" name="nome" autocomplete="off" placeholder="Produto:"></div>
            <div><input type="text" name="descricao" autocomplete="off" placeholder="Descrição do produto:"></div>
            <div><input type="number" name="valor" placeholder="Valor:"></div>
            <div class="button-submit"><input type="submit" value="Adicionar Produto"></div>
        </form>
    </div>
</body>

</html>

templates/cadastro_usuario.html
<!DOCTYPE html>
<html lang="pt-br">
 
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>S4 SUPRIMENTOS</title>
    <style>
        body {
            background: linear-gradient(to right, #ffffff, #ff6b00);
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
        }

        .header {
            background-color: #ececec;
            text-align: center;
            padding: 15px 0;
        }

        .header img {
            max-width: 100%;
            height: auto;
        }

        .separator {
            border-bottom: 1px solid rgb(60, 60, 60);
            box-shadow: 0 2px 4px rgb(37, 37, 37);
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            margin-top: 60px;
            margin-left: auto;
            margin-right: auto;
            padding: 20px;
            width: 315px;
            height: 300px;
            flex-direction: column;;
        }

        .button {
            text-decoration: none;
            display: flex;
            justify-content: center;
            align-items: center;
            width: 150px;
            height: 30px;
            margin-top: 50px;
            padding: 10px 20px;
            border-radius: 30px;
            border: none;
            background-color: #ff6b00;
            color: white;
            font-size: 16px;
            cursor: pointer;
            text-align: center;
        }

        .container {
            font-family: madefor-display, 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 22px;
        }

        input {
            font-size: 16px;
            margin-top: 30px;
            padding: 12px 20px;
            border-radius: 30px;
            border-color: #ff6b00;
        }

        .button-submit {
            cursor: pointer;
            display: flex;
            justify-content: center;
            cursor: pointer;
        }
    </style>
</head>

<body>
    <div class="header">
        <img
            src="https://static.wixstatic.com/media/b6c7e5_b6d43044bb344d83bb6a97a6875ea924~mv2.png/v1/crop/x_26,y_122,w_400,h_196/fill/w_112,h_55,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Nova%20Logo%20-%20s4.png">
    </div>
    <div class="separator"></div>
    <div class="container">Cadastrar Usuário
        <form action="{{ url_for('usuario_cadastro.cadastro_usuario')}}" method="post">
            <div><input type="email" name="email" autocomplete="off" placeholder="Email: supply_s4@exemplo.com"></div>
            <div><input type="password" name="senha" autocomplete="off" placeholder="Senha:"></div>
            <div class="button-submit"><input type="submit" value="Cadastrar"></div>
        </form>
    </div>
</body>

</html>

templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
   
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>S4 SUPRIMENTOS</title>
    <style>
      body {
        background: linear-gradient(to right, #ffffff, #ff6b00);
        margin: 0;
        font-family: Arial, sans-serif;
      }

    .header {
      background-color: #ececec;
      text-align: center;
      padding: 15px 0;
    }
    
    .header img {
      justify-content: center;
      align-items: center;
      max-width: 50%;
      height: auto;
      margin-left: 50px;
    }
    
    .sair {
      text-decoration: none;
      position: relative;
      left: 35%;
      top: -25px;
      background-color: #ff6b00;
      color: white;
      border: none;
      padding: 10px 20px;
      border-radius: 5px;
      box-shadow: inset 0 0 5px rgb(56, 56, 56);
      cursor: pointer;
    }

    .separator {
      border-bottom: 1px solid rgb(60, 60, 60);
      box-shadow: 0 2px 4px rgb(37, 37, 37);
    }
    
    .container {
      display: flex;
      align-items: center;
      margin-top: 60px;
      margin-left: auto;
      margin-right: auto;
      padding: 20px;
      width: 1015px;
      height: auto;
      border-radius: 20px;
      background-color: #ffffff;
      flex-direction: column;
      box-shadow: inset 0 0 10px rgb(180, 180, 180);
      font-family: madefor-display, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    }

    .button-create {
      display: flex;
      align-items: center;
      justify-content: center;
      color: #ff6b00;
      text-decoration: none;
      background-color: #ff6b00;
      width: 915px;
      height: 40px;
      border-radius: 20px;
      box-shadow: inset 0 0 5px rgb(80, 80, 80);
      margin-bottom: 20px;
      cursor: pointer;
    }

    .button-create::before {
      content: "+";
      font-size: 40px;
      display: inline-block;
      width: 35px;
      height: 35px;
      margin-left: 10px;
      border-radius: 50%;
      background-color: #fff;
      margin-right: 10px;
      line-height: 35px;
      text-align: center;
      box-shadow: inset 0 0 5px rgb(80, 80, 80);
      cursor: pointer;
    }

    .tabela {
      border-collapse: collapse;
      box-shadow: inset 0 0 5px rgb(155, 155, 155);
      padding: 10px;
      text-align: center;
      width: 915px;
    }

    .button-icon {
      color: #000;
      font-size: 25px;
      cursor: pointer;
    }
    
  </style>
</head>

<body>
  <div class="header">
    <img src="https://static.wixstatic.com/media/b6c7e5_b6d43044bb344d83bb6a97a6875ea924~mv2.png/v1/crop/x_26,y_122,w_400,h_196/fill/w_112,h_55,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Nova%20Logo%20-%20s4.png">
    <a href="/s4_suprimentos_cadastro_login" class="sair">Sair</a>
  </div>
  <div class="separator"></div>
  <div class="container">
    <a class="button-create" href="{{ url_for('cadastrar_routes.cadastrar_produto')}}"></a>
    <table border="1" class="tabela">
      <tr>
        <td>ID</td>
        <td>Produto</td>
        <td>Descrição</td>
        <td>Valor</td>
        <td>Excluir</td>
        <td>Atualizar</td>
      </tr>

      {% for produto in produtos %}

      <tr>
        <td>{{ produto.idProduto}}</td>
        <td>{{ produto.nome }}</td>
        <td>{{ produto.descricao }}</td>
        <td>{{ produto.valor }}</td>
        <td>
          <a class="button-icon" href="{{ url_for('excluir_routes.excluir', idProduto=produto.idProduto) }}">
            <ion-icon name="trash-outline"></ion-icon>
          </a>
        </td>
        <td>
          <a class="button-icon" href="{{ url_for('atualizar_routes.atualizar', idProduto=produto.idProduto) }}">
            <ion-icon name="refresh-circle-outline"></ion-icon>
          </a>
        </td>
      </tr>

      {% endfor %}
    </table>
  </div>
  <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>S4 SUPRIMENTOS</title>
    <style>
        body {
            background: linear-gradient(to right, #ffffff, #ff6b00);
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
        }

        .header {
            background-color: #ececec;
            text-align: center;
            padding: 15px 0;
        }

        .header img {
            max-width: 100%;
            height: auto;
        }

        .separator {
            border-bottom: 1px solid rgb(60, 60, 60);
            /* Reduzindo a espessura da linha */
            box-shadow: 0 2px 4px rgb(37, 37, 37);
            /* Ajustando o tamanho da sombra */
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            margin-top: 60px;
            margin-left: auto;
            margin-right: auto;
            padding: 20px;
            width: 315px;
            height: 300px;
            flex-direction: column;
            font-weight: bold;
            font-size: 20px;
        }

        .button {
            text-decoration: none;
            display: flex;
            justify-content: center;
            align-items: center;
            width: 150px;
            height: 30px;
            margin-top: 50px;
            padding: 10px 20px;
            border-radius: 30px;
            border: none;
            background-color: #ff6b00;
            color: white;
            font-size: 16px;
            cursor: pointer;
            text-align: center;
            font-family: madefor-display, 'Helvetica Neue', Helvetica, Arial, sans-serif;
        }

        .button-submit {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        input {
            font-size: 16px;
            margin-top: 30px;
            padding: 12px 20px;
            border-radius: 30px;
            border-color: #ff6b00;
        }

        form {
            justify-content: center;
            align-items: center;
        }
    </style>
</head>

<body>
    <div class="header">
        <img src="https://static.wixstatic.com/media/b6c7e5_b6d43044bb344d83bb6a97a6875ea924~mv2.png/v1/crop/x_26,y_122,w_400,h_196/fill/w_112,h_55,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Nova%20Logo%20-%20s4.png">
    </div>
    <div class="separator"></div>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert-flash"></div>
    <ul class=flashes>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    </div>
    {% endif %}
    {% endwith %}
    <div class="container">Entrar com Conta
        <form action="{{ url_for('usuario_login_routes.logar')}}" method="post">
            <div><input type="email" name="email" autocomplete="off" placeholder="Email: supplys4@exemplo.com"></div>
            <div><input type="password" name="senha" autocomplete="off" placeholder="Senha:"></div>
            <div class="button-submit"><input type="submit" value="Entrar"></div>
        </form>
    </div>
</body>

</html>

templates/pagina_login_cadastro.html
<!DOCTYPE html>
<html lang="pt-br">
 
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>S4 SUPRIMENTOS</title>

    <style>
        body {
            background: linear-gradient(to right, #ffffff, #ff6b00);
            margin: 0;
        }

        .header {
            background-color: #ececec;
            text-align: center;
            padding: 15px 0;
        }

        .header img {
            max-width: 100%;
            height: auto;
        }

        .separator {
            border-bottom: 1px solid rgb(60, 60, 60);
            /* Reduzindo a espessura da linha */
            box-shadow: 0 2px 4px rgb(37, 37, 37);
            /* Ajustando o tamanho da sombra */
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            margin-top: 50px;
            margin-left: auto;
            margin-right: auto;
            padding: 20px;
            height: 300px;
            border-radius: 20px;
        }

        a {
            cursor: pointer;
            text-decoration: none;
            display: flex;
            justify-content: center;
            align-items: center;
            width: 150px;
            height: 30px;
            margin-top: 40px;
            padding: 10px 20px;
            border-radius: 30px;
            background-color: #ff6b00;
            color: white;
            box-shadow: inset 0 0 5px rgb(60, 60, 60);
            font-family: madefor-display, 'Helvetica Neue', Helvetica, Arial, sans-serif;
            cursor: pointer;
        }

    </style>
</head>

<body>
    <div class="header">
        <img
            src="https://static.wixstatic.com/media/b6c7e5_b6d43044bb344d83bb6a97a6875ea924~mv2.png/v1/crop/x_26,y_122,w_400,h_196/fill/w_112,h_55,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Nova%20Logo%20-%20s4.png">
    </div>
    <div class="separator"></div>
    <div class="container">
        <div>
            <a href="{{ url_for('usuario_cadastro.cadastro_usuario')}}">Cadastrar</a>
            <a href="{{ url_for('usuario_login_routes.logar') }}">Entrar</a>
        </div>
    </div>
</body>

</html>